## YAML Template.
---

driver: "org.mariadb.jdbc.Driver"
sql: "meu_sql"
hosts:
-   dataBases: 
    - name: "ipathos_auditoria"
    - name: "ipathos_auditoria_20190218"
    host: "192.168.1.28"
    port: "3306"
    user: "app"
    password: "app"
-   dataBases:
    - name: "ipathos_auditoria"
    host: "192.168.1.31"
    port: "3306"
    user: "root"
    password: "root"
        